version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: soccerDb
      POSTGRES_PASSWORD: soccer
      POSTGRES_USER: dev
    ports:
      - 5432:5432